# Generated by Django 3.2.23 on 2023-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
